
import java.awt.Color;
import java.io.File;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Esquivel Oscar
 * @author Garbanzo Diana
 */
public class JFNotas extends javax.swing.JFrame {
    // Variables del JF para controlar las acciones
    private static ConexionProlog proyecto;
    private static String nombreArchivo;
    
    /**
     * Constructor del JFrame
     */
    public JFNotas() {
        super("Composión algorítmica");
        initComponents();
        inicializarVariables();
    }
    
    /**
     * Inicializa las variables de control del JFrame
     */
    private void inicializarVariables(){
        this.proyecto = new ConexionProlog();
        this.nombreArchivo = "";
        // Configuraciones de la interfaz
        setLayout(null);
        setSize(445,220);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAleatoria = new javax.swing.JButton();
        buttonEscogerArchivo = new javax.swing.JButton();
        jlArchivoSeleccionado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(454, 556));
        getContentPane().setLayout(null);

        buttonAleatoria.setText("Escuchar canción");
        buttonAleatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAleatoriaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAleatoria);
        buttonAleatoria.setBounds(220, 50, 190, 23);

        buttonEscogerArchivo.setText("Seleccionar archivo");
        buttonEscogerArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEscogerArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEscogerArchivo);
        buttonEscogerArchivo.setBounds(40, 50, 150, 23);

        jlArchivoSeleccionado.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jlArchivoSeleccionado);
        jlArchivoSeleccionado.setBounds(40, 80, 140, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/fondoInferior.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -470, 480, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param evt, no se utiliza
     * Evento asociado al boton de generar cancion aleatoria.
     * LLama a la regla asociada.
     */
    private void buttonAleatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAleatoriaActionPerformed
        // Llama a compositor para generar cancion de forma aleatoria 
        String[] notasYduraciones = proyecto.ejecutarConsulta(this.nombreArchivo,false);
        reproducirNotas(notasYduraciones);
    }//GEN-LAST:event_buttonAleatoriaActionPerformed

    private void buttonEscogerArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEscogerArchivoActionPerformed
        JFileChooser escogerArchivo = new JFileChooser();
        escogerArchivo.showOpenDialog(null);
        File archivoSeleccionado = escogerArchivo.getSelectedFile();
        this.nombreArchivo = archivoSeleccionado.getAbsolutePath();
        
        if(("").equals(nombreArchivo))
        {
            this.jlArchivoSeleccionado.setText("");
            this.jlArchivoSeleccionado.setVisible(false);
        }
        else
        {
            this.jlArchivoSeleccionado.setText(archivoSeleccionado.getName());
            this.jlArchivoSeleccionado.setVisible(true);
        }
    }//GEN-LAST:event_buttonEscogerArchivoActionPerformed
    
    private void reproducirNotas(String[] notasYduraciones)
    {
        Player player = new Player();
        player.playMusic(notasYduraciones);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAleatoria;
    private javax.swing.JButton buttonEscogerArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlArchivoSeleccionado;
    // End of variables declaration//GEN-END:variables
}
